export const vocabPart1 = [
  { kana:"わたし", romaji:"watashi", reading:"わたし", meaning:"I / me", type:"Pronoun" },
  { kana:"わたくし", romaji:"watakushi", reading:"わたくし", meaning:"I / me (formal)", type:"Pronoun" },
  { kana:"ぼく", romaji:"boku", reading:"ぼく", meaning:"I / me (male, casual)", type:"Pronoun" },
  { kana:"あたし", romaji:"atashi", reading:"あたし", meaning:"I / me (female, casual)", type:"Pronoun" },
  { kana:"あなた", romaji:"anata", reading:"あなた", meaning:"you", type:"Pronoun" },
  { kana:"かれ", romaji:"kare", reading:"かれ", meaning:"he / boyfriend", type:"Pronoun" },
  { kana:"かのじょ", romaji:"kanojo", reading:"かのじょ", meaning:"she / girlfriend", type:"Pronoun" },
  { kana:"わたしたち", romaji:"watashitachi", reading:"わたしたち", meaning:"we / us", type:"Pronoun" },
  { kana:"これ", romaji:"kore", reading:"これ", meaning:"this (near speaker)", type:"Pronoun" },
  { kana:"それ", romaji:"sore", reading:"それ", meaning:"that (near listener)", type:"Pronoun" },
  { kana:"あれ", romaji:"are", reading:"あれ", meaning:"that (far away)", type:"Pronoun" },
  { kana:"どれ", romaji:"dore", reading:"どれ", meaning:"which one", type:"Pronoun" },
  { kana:"この", romaji:"kono", reading:"この", meaning:"this ~", type:"Demonstrative" },
  { kana:"その", romaji:"sono", reading:"その", meaning:"that ~", type:"Demonstrative" },
  { kana:"あの", romaji:"ano", reading:"あの", meaning:"that ~ (far)", type:"Demonstrative" },
  { kana:"どの", romaji:"dono", reading:"どの", meaning:"which ~", type:"Demonstrative" },
  { kana:"ここ", romaji:"koko", reading:"ここ", meaning:"here", type:"Pronoun" },
  { kana:"そこ", romaji:"soko", reading:"そこ", meaning:"there", type:"Pronoun" },
  { kana:"あそこ", romaji:"asoko", reading:"あそこ", meaning:"over there", type:"Pronoun" },
  { kana:"どこ", romaji:"doko", reading:"どこ", meaning:"where", type:"Pronoun" },
  { kana:"こちら", romaji:"kochira", reading:"こちら", meaning:"this way / here", type:"Pronoun" },
  { kana:"そちら", romaji:"sochira", reading:"そちら", meaning:"that way / there", type:"Pronoun" },
  { kana:"あちら", romaji:"achira", reading:"あちら", meaning:"over there (direction)", type:"Pronoun" },
  { kana:"どちら", romaji:"dochira", reading:"どちら", meaning:"which way / where", type:"Pronoun" },
  { kana:"だれ", romaji:"dare", reading:"だれ", meaning:"who", type:"Pronoun" },
  { kana:"なに・なん", romaji:"nani / nan", reading:"なに・なん", meaning:"what", type:"Pronoun" },
  { kana:"いつ", romaji:"itsu", reading:"いつ", meaning:"when", type:"Pronoun" },
  { kana:"なぜ", romaji:"naze", reading:"なぜ", meaning:"why", type:"Pronoun" },
  { kana:"どう", romaji:"dou", reading:"どう", meaning:"how", type:"Pronoun" },
  { kana:"いくら", romaji:"ikura", reading:"いくら", meaning:"how much", type:"Pronoun" },
  { kana:"おはよう", romaji:"ohayou", reading:"おはよう", meaning:"good morning (casual)", type:"Expression" },
  { kana:"おはようございます", romaji:"ohayou gozaimasu", reading:"おはようございます", meaning:"good morning (formal)", type:"Expression" },
  { kana:"こんにちは", romaji:"konnichiwa", reading:"こんにちは", meaning:"hello / good afternoon", type:"Expression" },
  { kana:"こんばんは", romaji:"konbanwa", reading:"こんばんは", meaning:"good evening", type:"Expression" },
  { kana:"おやすみなさい", romaji:"oyasuminasai", reading:"おやすみなさい", meaning:"good night", type:"Expression" },
  { kana:"さようなら", romaji:"sayounara", reading:"さようなら", meaning:"goodbye", type:"Expression" },
  { kana:"じゃあ", romaji:"jaa", reading:"じゃあ", meaning:"well then / see you", type:"Expression" },
  { kana:"ありがとう", romaji:"arigatou", reading:"ありがとう", meaning:"thank you (casual)", type:"Expression" },
  { kana:"ありがとうございます", romaji:"arigatou gozaimasu", reading:"ありがとうございます", meaning:"thank you (formal)", type:"Expression" },
  { kana:"すみません", romaji:"sumimasen", reading:"すみません", meaning:"excuse me / I'm sorry", type:"Expression" },
  { kana:"ごめんなさい", romaji:"gomen nasai", reading:"ごめんなさい", meaning:"I'm sorry", type:"Expression" },
  { kana:"はい", romaji:"hai", reading:"はい", meaning:"yes", type:"Expression" },
  { kana:"いいえ", romaji:"iie", reading:"いいえ", meaning:"no", type:"Expression" },
  { kana:"どうぞ", romaji:"douzo", reading:"どうぞ", meaning:"please / go ahead", type:"Expression" },
  { kana:"どうも", romaji:"doumo", reading:"どうも", meaning:"thanks / hi", type:"Expression" },
  { kana:"いただきます", romaji:"itadakimasu", reading:"いただきます", meaning:"let's eat (before meal)", type:"Expression" },
  { kana:"ごちそうさま", romaji:"gochisousama", reading:"ごちそうさま", meaning:"thanks for the meal (after)", type:"Expression" },
  { kana:"はじめまして", romaji:"hajimemashite", reading:"はじめまして", meaning:"nice to meet you", type:"Expression" },
  { kana:"よろしくおねがいします", romaji:"yoroshiku onegaishimasu", reading:"よろしくおねがいします", meaning:"pleased to meet you / please", type:"Expression" },
  { kana:"おねがいします", romaji:"onegaishimasu", reading:"おねがいします", meaning:"please (request)", type:"Expression" },
  { kana:"わかりました", romaji:"wakarimashita", reading:"わかりました", meaning:"I understand / understood", type:"Expression" },
  { kana:"わかりません", romaji:"wakarimasen", reading:"わかりません", meaning:"I don't understand", type:"Expression" },
  { kana:"そうですか", romaji:"sou desu ka", reading:"そうですか", meaning:"is that so? / really?", type:"Expression" },
  { kana:"そうです", romaji:"sou desu", reading:"そうです", meaning:"that's right", type:"Expression" },
  { kana:"ただいま", romaji:"tadaima", reading:"ただいま", meaning:"I'm home", type:"Expression" },
  { kana:"おかえり", romaji:"okaeri", reading:"おかえり", meaning:"welcome home", type:"Expression" },
  { kana:"いってきます", romaji:"ittekimasu", reading:"いってきます", meaning:"I'm going (and will return)", type:"Expression" },
  { kana:"いってらっしゃい", romaji:"itterasshai", reading:"いってらっしゃい", meaning:"take care / have a safe trip", type:"Expression" },
  { kana:"もう一度おねがいします", romaji:"mou ichido onegaishimasu", reading:"もういちどおねがいします", meaning:"please say that again", type:"Expression" },
  { kana:"ひと", romaji:"hito", reading:"ひと", meaning:"person", type:"Noun" },
  { kana:"おとこ", romaji:"otoko", reading:"おとこ", meaning:"man / male", type:"Noun" },
  { kana:"おんな", romaji:"onna", reading:"おんな", meaning:"woman / female", type:"Noun" },
  { kana:"おとこのこ", romaji:"otoko no ko", reading:"おとこのこ", meaning:"boy", type:"Noun" },
  { kana:"おんなのこ", romaji:"onna no ko", reading:"おんなのこ", meaning:"girl", type:"Noun" },
  { kana:"こども", romaji:"kodomo", reading:"こども", meaning:"child", type:"Noun" },
  { kana:"おとな", romaji:"otona", reading:"おとな", meaning:"adult", type:"Noun" },
  { kana:"ともだち", romaji:"tomodachi", reading:"ともだち", meaning:"friend", type:"Noun" },
  { kana:"みなさん", romaji:"minasan", reading:"みなさん", meaning:"everyone", type:"Noun" },
  { kana:"かた", romaji:"kata", reading:"かた", meaning:"person (polite)", type:"Noun" },
  { kana:"りょうしん", romaji:"ryoushin", reading:"りょうしん", meaning:"parents", type:"Noun" },
  { kana:"きょうだい", romaji:"kyoudai", reading:"きょうだい", meaning:"siblings", type:"Noun" },
  { kana:"かぞく", romaji:"kazoku", reading:"かぞく", meaning:"family", type:"Noun" },
  { kana:"ちち", romaji:"chichi", reading:"ちち", meaning:"(my) father", type:"Noun" },
  { kana:"はは", romaji:"haha", reading:"はは", meaning:"(my) mother", type:"Noun" },
  { kana:"おとうさん", romaji:"otousan", reading:"おとうさん", meaning:"father (respectful)", type:"Noun" },
  { kana:"おかあさん", romaji:"okaasan", reading:"おかあさん", meaning:"mother (respectful)", type:"Noun" },
  { kana:"あに", romaji:"ani", reading:"あに", meaning:"(my) older brother", type:"Noun" },
  { kana:"あね", romaji:"ane", reading:"あね", meaning:"(my) older sister", type:"Noun" },
  { kana:"おとうと", romaji:"otouto", reading:"おとうと", meaning:"younger brother", type:"Noun" },
  { kana:"いもうと", romaji:"imouto", reading:"いもうと", meaning:"younger sister", type:"Noun" },
  { kana:"おにいさん", romaji:"oniisan", reading:"おにいさん", meaning:"older brother (respectful)", type:"Noun" },
  { kana:"おねえさん", romaji:"oneesan", reading:"おねえさん", meaning:"older sister (respectful)", type:"Noun" },
  { kana:"そふ", romaji:"sofu", reading:"そふ", meaning:"(my) grandfather", type:"Noun" },
  { kana:"そぼ", romaji:"sobo", reading:"そぼ", meaning:"(my) grandmother", type:"Noun" },
  { kana:"おじいさん", romaji:"ojiisan", reading:"おじいさん", meaning:"grandfather (respectful)", type:"Noun" },
  { kana:"おばあさん", romaji:"obaasan", reading:"おばあさん", meaning:"grandmother (respectful)", type:"Noun" },
  { kana:"おじさん", romaji:"ojisan", reading:"おじさん", meaning:"uncle / middle-aged man", type:"Noun" },
  { kana:"おばさん", romaji:"obasan", reading:"おばさん", meaning:"aunt / middle-aged woman", type:"Noun" },
  { kana:"むすこ", romaji:"musuko", reading:"むすこ", meaning:"(my) son", type:"Noun" },
  { kana:"むすめ", romaji:"musume", reading:"むすめ", meaning:"(my) daughter", type:"Noun" },
  { kana:"しゅじん", romaji:"shujin", reading:"しゅじん", meaning:"(my) husband", type:"Noun" },
  { kana:"かない", romaji:"kanai", reading:"かない", meaning:"(my) wife", type:"Noun" },
  { kana:"ごしゅじん", romaji:"goshujin", reading:"ごしゅじん", meaning:"(your) husband", type:"Noun" },
  { kana:"おくさん", romaji:"okusan", reading:"おくさん", meaning:"(your) wife", type:"Noun" },
  { kana:"からだ", romaji:"karada", reading:"からだ", meaning:"body", type:"Noun" },
  { kana:"あたま", romaji:"atama", reading:"あたま", meaning:"head", type:"Noun" },
  { kana:"かみ（髪）", romaji:"kami", reading:"かみ", meaning:"hair", type:"Noun" },
  { kana:"かお", romaji:"kao", reading:"かお", meaning:"face", type:"Noun" },
  { kana:"め", romaji:"me", reading:"め", meaning:"eye(s)", type:"Noun" },
  { kana:"みみ", romaji:"mimi", reading:"みみ", meaning:"ear(s)", type:"Noun" },
  { kana:"はな（鼻）", romaji:"hana", reading:"はな", meaning:"nose", type:"Noun" },
  { kana:"くち", romaji:"kuchi", reading:"くち", meaning:"mouth", type:"Noun" },
  { kana:"は", romaji:"ha", reading:"は", meaning:"tooth / teeth", type:"Noun" },
  { kana:"くび", romaji:"kubi", reading:"くび", meaning:"neck", type:"Noun" },
  { kana:"むね", romaji:"mune", reading:"むね", meaning:"chest", type:"Noun" },
  { kana:"おなか", romaji:"onaka", reading:"おなか", meaning:"stomach / belly", type:"Noun" },
  { kana:"せなか", romaji:"senaka", reading:"せなか", meaning:"back", type:"Noun" },
  { kana:"て", romaji:"te", reading:"て", meaning:"hand / arm", type:"Noun" },
  { kana:"ゆび", romaji:"yubi", reading:"ゆび", meaning:"finger", type:"Noun" },
  { kana:"あし", romaji:"ashi", reading:"あし", meaning:"leg / foot", type:"Noun" },
  { kana:"こし", romaji:"koshi", reading:"こし", meaning:"waist / hip", type:"Noun" },
  { kana:"こえ", romaji:"koe", reading:"こえ", meaning:"voice", type:"Noun" },
  { kana:"ふく", romaji:"fuku", reading:"ふく", meaning:"clothes", type:"Noun" },
  { kana:"シャツ", romaji:"shatsu", reading:"シャツ", meaning:"shirt", type:"Noun" },
  { kana:"ズボン", romaji:"zubon", reading:"ズボン", meaning:"pants / trousers", type:"Noun" },
  { kana:"スカート", romaji:"sukaato", reading:"スカート", meaning:"skirt", type:"Noun" },
  { kana:"ジャケット", romaji:"jaketto", reading:"ジャケット", meaning:"jacket", type:"Noun" },
  { kana:"コート", romaji:"kooto", reading:"コート", meaning:"coat", type:"Noun" },
  { kana:"くつ", romaji:"kutsu", reading:"くつ", meaning:"shoes", type:"Noun" },
  { kana:"くつした", romaji:"kutsushita", reading:"くつした", meaning:"socks", type:"Noun" },
  { kana:"ぼうし", romaji:"boushi", reading:"ぼうし", meaning:"hat / cap", type:"Noun" },
  { kana:"めがね", romaji:"megane", reading:"めがね", meaning:"glasses", type:"Noun" },
  { kana:"かばん", romaji:"kaban", reading:"かばん", meaning:"bag", type:"Noun" },
  { kana:"さいふ", romaji:"saifu", reading:"さいふ", meaning:"wallet", type:"Noun" },
  { kana:"とけい", romaji:"tokei", reading:"とけい", meaning:"watch / clock", type:"Noun" },
  { kana:"ネクタイ", romaji:"nekutai", reading:"ネクタイ", meaning:"tie", type:"Noun" },
  { kana:"セーター", romaji:"seetaa", reading:"セーター", meaning:"sweater", type:"Noun" },
  { kana:"てぶくろ", romaji:"tebukuro", reading:"てぶくろ", meaning:"gloves", type:"Noun" },
  { kana:"たべもの", romaji:"tabemono", reading:"たべもの", meaning:"food", type:"Noun" },
  { kana:"のみもの", romaji:"nomimono", reading:"のみもの", meaning:"drink / beverage", type:"Noun" },
  { kana:"ごはん", romaji:"gohan", reading:"ごはん", meaning:"cooked rice / meal", type:"Noun" },
  { kana:"パン", romaji:"pan", reading:"パン", meaning:"bread", type:"Noun" },
  { kana:"うどん", romaji:"udon", reading:"うどん", meaning:"udon noodles", type:"Noun" },
  { kana:"そば", romaji:"soba", reading:"そば", meaning:"soba noodles", type:"Noun" },
  { kana:"ラーメン", romaji:"raamen", reading:"ラーメン", meaning:"ramen", type:"Noun" },
  { kana:"すし", romaji:"sushi", reading:"すし", meaning:"sushi", type:"Noun" },
  { kana:"てんぷら", romaji:"tenpura", reading:"てんぷら", meaning:"tempura", type:"Noun" },
  { kana:"とんかつ", romaji:"tonkatsu", reading:"とんかつ", meaning:"pork cutlet", type:"Noun" },
  { kana:"カレー", romaji:"karee", reading:"カレー", meaning:"curry", type:"Noun" },
  { kana:"さかな", romaji:"sakana", reading:"さかな", meaning:"fish", type:"Noun" },
  { kana:"にく", romaji:"niku", reading:"にく", meaning:"meat", type:"Noun" },
  { kana:"とりにく", romaji:"toriniku", reading:"とりにく", meaning:"chicken meat", type:"Noun" },
  { kana:"ぎゅうにく", romaji:"gyuuniku", reading:"ぎゅうにく", meaning:"beef", type:"Noun" },
  { kana:"ぶたにく", romaji:"butaniku", reading:"ぶたにく", meaning:"pork", type:"Noun" },
  { kana:"たまご", romaji:"tamago", reading:"たまご", meaning:"egg", type:"Noun" },
  { kana:"やさい", romaji:"yasai", reading:"やさい", meaning:"vegetables", type:"Noun" },
  { kana:"くだもの", romaji:"kudamono", reading:"くだもの", meaning:"fruit", type:"Noun" },
  { kana:"りんご", romaji:"ringo", reading:"りんご", meaning:"apple", type:"Noun" },
  { kana:"バナナ", romaji:"banana", reading:"バナナ", meaning:"banana", type:"Noun" },
  { kana:"みかん", romaji:"mikan", reading:"みかん", meaning:"mandarin orange", type:"Noun" },
  { kana:"ぶどう", romaji:"budou", reading:"ぶどう", meaning:"grapes", type:"Noun" },
  { kana:"いちご", romaji:"ichigo", reading:"いちご", meaning:"strawberry", type:"Noun" },
  { kana:"トマト", romaji:"tomato", reading:"トマト", meaning:"tomato", type:"Noun" },
  { kana:"きゅうり", romaji:"kyuuri", reading:"きゅうり", meaning:"cucumber", type:"Noun" },
  { kana:"たまねぎ", romaji:"tamanegi", reading:"たまねぎ", meaning:"onion", type:"Noun" },
  { kana:"にんじん", romaji:"ninjin", reading:"にんじん", meaning:"carrot", type:"Noun" },
  { kana:"じゃがいも", romaji:"jagaimo", reading:"じゃがいも", meaning:"potato", type:"Noun" },
  { kana:"キャベツ", romaji:"kyabetsu", reading:"キャベツ", meaning:"cabbage", type:"Noun" },
  { kana:"みそしる", romaji:"misoshiru", reading:"みそしる", meaning:"miso soup", type:"Noun" },
  { kana:"サラダ", romaji:"sarada", reading:"サラダ", meaning:"salad", type:"Noun" },
  { kana:"スープ", romaji:"suupu", reading:"スープ", meaning:"soup", type:"Noun" },
  { kana:"ケーキ", romaji:"keeki", reading:"ケーキ", meaning:"cake", type:"Noun" },
  { kana:"おかし", romaji:"okashi", reading:"おかし", meaning:"sweets / snacks", type:"Noun" },
  { kana:"チョコレート", romaji:"chokoreeto", reading:"チョコレート", meaning:"chocolate", type:"Noun" },
  { kana:"しお", romaji:"shio", reading:"しお", meaning:"salt", type:"Noun" },
  { kana:"さとう", romaji:"satou", reading:"さとう", meaning:"sugar", type:"Noun" },
  { kana:"しょうゆ", romaji:"shouyu", reading:"しょうゆ", meaning:"soy sauce", type:"Noun" },
  { kana:"バター", romaji:"bataa", reading:"バター", meaning:"butter", type:"Noun" },
  { kana:"みず", romaji:"mizu", reading:"みず", meaning:"water", type:"Noun" },
  { kana:"おちゃ", romaji:"ocha", reading:"おちゃ", meaning:"green tea", type:"Noun" },
  { kana:"こうちゃ", romaji:"koucha", reading:"こうちゃ", meaning:"black tea", type:"Noun" },
  { kana:"コーヒー", romaji:"koohii", reading:"コーヒー", meaning:"coffee", type:"Noun" },
  { kana:"ジュース", romaji:"juusu", reading:"ジュース", meaning:"juice", type:"Noun" },
  { kana:"ぎゅうにゅう", romaji:"gyuunyuu", reading:"ぎゅうにゅう", meaning:"milk", type:"Noun" },
  { kana:"ビール", romaji:"biiru", reading:"ビール", meaning:"beer", type:"Noun" },
  { kana:"おさけ", romaji:"osake", reading:"おさけ", meaning:"alcohol / sake", type:"Noun" },
  { kana:"コーラ", romaji:"koora", reading:"コーラ", meaning:"cola", type:"Noun" },
  { kana:"もの", romaji:"mono", reading:"もの", meaning:"thing / object", type:"Noun" },
  { kana:"つくえ", romaji:"tsukue", reading:"つくえ", meaning:"desk", type:"Noun" },
  { kana:"いす", romaji:"isu", reading:"いす", meaning:"chair", type:"Noun" },
  { kana:"テーブル", romaji:"teeburu", reading:"テーブル", meaning:"table", type:"Noun" },
  { kana:"ベッド", romaji:"beddo", reading:"ベッド", meaning:"bed", type:"Noun" },
  { kana:"まど", romaji:"mado", reading:"まど", meaning:"window", type:"Noun" },
  { kana:"ドア", romaji:"doa", reading:"ドア", meaning:"door", type:"Noun" },
  { kana:"でんき", romaji:"denki", reading:"でんき", meaning:"electricity / light", type:"Noun" },
  { kana:"テレビ", romaji:"terebi", reading:"テレビ", meaning:"television", type:"Noun" },
  { kana:"ラジオ", romaji:"rajio", reading:"ラジオ", meaning:"radio", type:"Noun" },
  { kana:"パソコン", romaji:"pasokon", reading:"パソコン", meaning:"personal computer", type:"Noun" },
  { kana:"でんわ", romaji:"denwa", reading:"でんわ", meaning:"telephone", type:"Noun" },
  { kana:"けいたいでんわ", romaji:"keitai denwa", reading:"けいたいでんわ", meaning:"cell phone", type:"Noun" },
  { kana:"スマートフォン", romaji:"sumaatofon", reading:"スマートフォン", meaning:"smartphone", type:"Noun" },
  { kana:"ほん", romaji:"hon", reading:"ほん", meaning:"book", type:"Noun" },
  { kana:"ざっし", romaji:"zasshi", reading:"ざっし", meaning:"magazine", type:"Noun" },
  { kana:"しんぶん", romaji:"shinbun", reading:"しんぶん", meaning:"newspaper", type:"Noun" },
  { kana:"てがみ", romaji:"tegami", reading:"てがみ", meaning:"letter", type:"Noun" },
  { kana:"はがき", romaji:"hagaki", reading:"はがき", meaning:"postcard", type:"Noun" },
  { kana:"きって", romaji:"kitte", reading:"きって", meaning:"stamp", type:"Noun" },
  { kana:"えんぴつ", romaji:"enpitsu", reading:"えんぴつ", meaning:"pencil", type:"Noun" },
  { kana:"ボールペン", romaji:"boorupen", reading:"ボールペン", meaning:"ballpoint pen", type:"Noun" },
  { kana:"ノート", romaji:"nooto", reading:"ノート", meaning:"notebook", type:"Noun" },
  { kana:"かみ（紙）", romaji:"kami", reading:"かみ", meaning:"paper", type:"Noun" },
  { kana:"はさみ", romaji:"hasami", reading:"はさみ", meaning:"scissors", type:"Noun" },
  { kana:"じしょ", romaji:"jisho", reading:"じしょ", meaning:"dictionary", type:"Noun" },
  { kana:"かさ", romaji:"kasa", reading:"かさ", meaning:"umbrella", type:"Noun" },
  { kana:"かぎ", romaji:"kagi", reading:"かぎ", meaning:"key", type:"Noun" },
  { kana:"はこ", romaji:"hako", reading:"はこ", meaning:"box", type:"Noun" },
  { kana:"コップ", romaji:"koppu", reading:"コップ", meaning:"cup / glass", type:"Noun" },
  { kana:"おさら", romaji:"osara", reading:"おさら", meaning:"plate / dish", type:"Noun" },
  { kana:"はし", romaji:"hashi", reading:"はし", meaning:"chopsticks", type:"Noun" },
  { kana:"スプーン", romaji:"supuun", reading:"スプーン", meaning:"spoon", type:"Noun" },
  { kana:"フォーク", romaji:"fooku", reading:"フォーク", meaning:"fork", type:"Noun" },
  { kana:"ナイフ", romaji:"naifu", reading:"ナイフ", meaning:"knife", type:"Noun" },
  { kana:"カメラ", romaji:"kamera", reading:"カメラ", meaning:"camera", type:"Noun" },
  { kana:"れいぞうこ", romaji:"reizouko", reading:"れいぞうこ", meaning:"refrigerator", type:"Noun" },
  { kana:"せんたっき", romaji:"sentakki", reading:"せんたっき", meaning:"washing machine", type:"Noun" },
  { kana:"おふろ", romaji:"ofuro", reading:"おふろ", meaning:"bath", type:"Noun" },
  { kana:"トイレ", romaji:"toire", reading:"トイレ", meaning:"toilet / restroom", type:"Noun" },
  { kana:"へや", romaji:"heya", reading:"へや", meaning:"room", type:"Noun" },
  { kana:"にわ", romaji:"niwa", reading:"にわ", meaning:"garden / yard", type:"Noun" },
  { kana:"かべ", romaji:"kabe", reading:"かべ", meaning:"wall", type:"Noun" },
  { kana:"ゆか", romaji:"yuka", reading:"ゆか", meaning:"floor", type:"Noun" },
  { kana:"かいだん", romaji:"kaidan", reading:"かいだん", meaning:"stairs", type:"Noun" },
  { kana:"ふとん", romaji:"futon", reading:"ふとん", meaning:"futon / bedding", type:"Noun" },
  { kana:"まくら", romaji:"makura", reading:"まくら", meaning:"pillow", type:"Noun" },
  { kana:"タオル", romaji:"taoru", reading:"タオル", meaning:"towel", type:"Noun" },
  { kana:"せっけん", romaji:"sekken", reading:"せっけん", meaning:"soap", type:"Noun" },
  { kana:"かがみ", romaji:"kagami", reading:"かがみ", meaning:"mirror", type:"Noun" },
  { kana:"ごみ", romaji:"gomi", reading:"ごみ", meaning:"trash / garbage", type:"Noun" },
  { kana:"でんち", romaji:"denchi", reading:"でんち", meaning:"battery", type:"Noun" },
];
