export const vocabPart2 = [
  { kana:"いえ・うち", romaji:"ie / uchi", reading:"いえ・うち", meaning:"house / home", type:"Noun" },
  { kana:"アパート", romaji:"apaato", reading:"アパート", meaning:"apartment", type:"Noun" },
  { kana:"マンション", romaji:"manshon", reading:"マンション", meaning:"condominium", type:"Noun" },
  { kana:"がっこう", romaji:"gakkou", reading:"がっこう", meaning:"school", type:"Noun" },
  { kana:"だいがく", romaji:"daigaku", reading:"だいがく", meaning:"university", type:"Noun" },
  { kana:"しょうがっこう", romaji:"shougakkou", reading:"しょうがっこう", meaning:"elementary school", type:"Noun" },
  { kana:"ちゅうがっこう", romaji:"chuugakkou", reading:"ちゅうがっこう", meaning:"middle school", type:"Noun" },
  { kana:"こうこう", romaji:"koukou", reading:"こうこう", meaning:"high school", type:"Noun" },
  { kana:"としょかん", romaji:"toshokan", reading:"としょかん", meaning:"library", type:"Noun" },
  { kana:"びょういん", romaji:"byouin", reading:"びょういん", meaning:"hospital", type:"Noun" },
  { kana:"やっきょく", romaji:"yakkyoku", reading:"やっきょく", meaning:"pharmacy", type:"Noun" },
  { kana:"ゆうびんきょく", romaji:"yuubinkyoku", reading:"ゆうびんきょく", meaning:"post office", type:"Noun" },
  { kana:"ぎんこう", romaji:"ginkou", reading:"ぎんこう", meaning:"bank", type:"Noun" },
  { kana:"みせ", romaji:"mise", reading:"みせ", meaning:"shop / store", type:"Noun" },
  { kana:"スーパー", romaji:"suupaa", reading:"スーパー", meaning:"supermarket", type:"Noun" },
  { kana:"デパート", romaji:"depaato", reading:"デパート", meaning:"department store", type:"Noun" },
  { kana:"レストラン", romaji:"resutoran", reading:"レストラン", meaning:"restaurant", type:"Noun" },
  { kana:"コンビニ", romaji:"konbini", reading:"コンビニ", meaning:"convenience store", type:"Noun" },
  { kana:"こうえん", romaji:"kouen", reading:"こうえん", meaning:"park", type:"Noun" },
  { kana:"えき", romaji:"eki", reading:"えき", meaning:"station", type:"Noun" },
  { kana:"くうこう", romaji:"kuukou", reading:"くうこう", meaning:"airport", type:"Noun" },
  { kana:"みなと", romaji:"minato", reading:"みなと", meaning:"harbor / port", type:"Noun" },
  { kana:"みち", romaji:"michi", reading:"みち", meaning:"road / street", type:"Noun" },
  { kana:"まち", romaji:"machi", reading:"まち", meaning:"town / city", type:"Noun" },
  { kana:"むら", romaji:"mura", reading:"むら", meaning:"village", type:"Noun" },
  { kana:"くに", romaji:"kuni", reading:"くに", meaning:"country / nation", type:"Noun" },
  { kana:"かいしゃ", romaji:"kaisha", reading:"かいしゃ", meaning:"company", type:"Noun" },
  { kana:"きょうしつ", romaji:"kyoushitsu", reading:"きょうしつ", meaning:"classroom", type:"Noun" },
  { kana:"プール", romaji:"puuru", reading:"プール", meaning:"swimming pool", type:"Noun" },
  { kana:"ホテル", romaji:"hoteru", reading:"ホテル", meaning:"hotel", type:"Noun" },
  { kana:"びじゅつかん", romaji:"bijutsukan", reading:"びじゅつかん", meaning:"art museum", type:"Noun" },
  { kana:"どうぶつえん", romaji:"doubutsuen", reading:"どうぶつえん", meaning:"zoo", type:"Noun" },
  { kana:"でんしゃ", romaji:"densha", reading:"でんしゃ", meaning:"train", type:"Noun" },
  { kana:"バス", romaji:"basu", reading:"バス", meaning:"bus", type:"Noun" },
  { kana:"タクシー", romaji:"takushii", reading:"タクシー", meaning:"taxi", type:"Noun" },
  { kana:"じてんしゃ", romaji:"jitensha", reading:"じてんしゃ", meaning:"bicycle", type:"Noun" },
  { kana:"くるま", romaji:"kuruma", reading:"くるま", meaning:"car", type:"Noun" },
  { kana:"バイク", romaji:"baiku", reading:"バイク", meaning:"motorcycle", type:"Noun" },
  { kana:"ひこうき", romaji:"hikouki", reading:"ひこうき", meaning:"airplane", type:"Noun" },
  { kana:"ふね", romaji:"fune", reading:"ふね", meaning:"boat / ship", type:"Noun" },
  { kana:"ちかてつ", romaji:"chikatetsu", reading:"ちかてつ", meaning:"subway", type:"Noun" },
  { kana:"しんかんせん", romaji:"shinkansen", reading:"しんかんせん", meaning:"bullet train", type:"Noun" },
  { kana:"きっぷ", romaji:"kippu", reading:"きっぷ", meaning:"ticket", type:"Noun" },
  { kana:"ていりゅうじょ", romaji:"teiryuujo", reading:"ていりゅうじょ", meaning:"bus stop", type:"Noun" },
  { kana:"ホーム", romaji:"hoomu", reading:"ホーム", meaning:"(train) platform", type:"Noun" },
  { kana:"じかん", romaji:"jikan", reading:"じかん", meaning:"time / hours", type:"Noun" },
  { kana:"いま", romaji:"ima", reading:"いま", meaning:"now", type:"Noun" },
  { kana:"きょう", romaji:"kyou", reading:"きょう", meaning:"today", type:"Noun" },
  { kana:"きのう", romaji:"kinou", reading:"きのう", meaning:"yesterday", type:"Noun" },
  { kana:"あした", romaji:"ashita", reading:"あした", meaning:"tomorrow", type:"Noun" },
  { kana:"おととい", romaji:"ototoi", reading:"おととい", meaning:"day before yesterday", type:"Noun" },
  { kana:"あさって", romaji:"asatte", reading:"あさって", meaning:"day after tomorrow", type:"Noun" },
  { kana:"ことし", romaji:"kotoshi", reading:"ことし", meaning:"this year", type:"Noun" },
  { kana:"きょねん", romaji:"kyonen", reading:"きょねん", meaning:"last year", type:"Noun" },
  { kana:"らいねん", romaji:"rainen", reading:"らいねん", meaning:"next year", type:"Noun" },
  { kana:"こんしゅう", romaji:"konshuu", reading:"こんしゅう", meaning:"this week", type:"Noun" },
  { kana:"せんしゅう", romaji:"senshuu", reading:"せんしゅう", meaning:"last week", type:"Noun" },
  { kana:"らいしゅう", romaji:"raishuu", reading:"らいしゅう", meaning:"next week", type:"Noun" },
  { kana:"こんげつ", romaji:"kongetsu", reading:"こんげつ", meaning:"this month", type:"Noun" },
  { kana:"せんげつ", romaji:"sengetsu", reading:"せんげつ", meaning:"last month", type:"Noun" },
  { kana:"らいげつ", romaji:"raigetsu", reading:"らいげつ", meaning:"next month", type:"Noun" },
  { kana:"あさ", romaji:"asa", reading:"あさ", meaning:"morning", type:"Noun" },
  { kana:"ひる", romaji:"hiru", reading:"ひる", meaning:"noon / daytime", type:"Noun" },
  { kana:"よる", romaji:"yoru", reading:"よる", meaning:"night / evening", type:"Noun" },
  { kana:"ばん", romaji:"ban", reading:"ばん", meaning:"evening / night", type:"Noun" },
  { kana:"まよなか", romaji:"mayonaka", reading:"まよなか", meaning:"midnight", type:"Noun" },
  { kana:"ごご", romaji:"gogo", reading:"ごご", meaning:"afternoon / PM", type:"Noun" },
  { kana:"ごぜん", romaji:"gozen", reading:"ごぜん", meaning:"morning / AM", type:"Noun" },
  { kana:"たんじょうび", romaji:"tanjoubi", reading:"たんじょうび", meaning:"birthday", type:"Noun" },
  { kana:"やすみ", romaji:"yasumi", reading:"やすみ", meaning:"holiday / vacation / rest", type:"Noun" },
  { kana:"しゅうまつ", romaji:"shuumatsu", reading:"しゅうまつ", meaning:"weekend", type:"Noun" },
  { kana:"にちようび", romaji:"nichiyoubi", reading:"にちようび", meaning:"Sunday", type:"Noun" },
  { kana:"げつようび", romaji:"getsuyoubi", reading:"げつようび", meaning:"Monday", type:"Noun" },
  { kana:"かようび", romaji:"kayoubi", reading:"かようび", meaning:"Tuesday", type:"Noun" },
  { kana:"すいようび", romaji:"suiyoubi", reading:"すいようび", meaning:"Wednesday", type:"Noun" },
  { kana:"もくようび", romaji:"mokuyoubi", reading:"もくようび", meaning:"Thursday", type:"Noun" },
  { kana:"きんようび", romaji:"kin'youbi", reading:"きんようび", meaning:"Friday", type:"Noun" },
  { kana:"どようび", romaji:"doyoubi", reading:"どようび", meaning:"Saturday", type:"Noun" },
  { kana:"いちがつ", romaji:"ichigatsu", reading:"いちがつ", meaning:"January", type:"Noun" },
  { kana:"にがつ", romaji:"nigatsu", reading:"にがつ", meaning:"February", type:"Noun" },
  { kana:"さんがつ", romaji:"sangatsu", reading:"さんがつ", meaning:"March", type:"Noun" },
  { kana:"しがつ", romaji:"shigatsu", reading:"しがつ", meaning:"April", type:"Noun" },
  { kana:"ごがつ", romaji:"gogatsu", reading:"ごがつ", meaning:"May", type:"Noun" },
  { kana:"ろくがつ", romaji:"rokugatsu", reading:"ろくがつ", meaning:"June", type:"Noun" },
  { kana:"しちがつ", romaji:"shichigatsu", reading:"しちがつ", meaning:"July", type:"Noun" },
  { kana:"はちがつ", romaji:"hachigatsu", reading:"はちがつ", meaning:"August", type:"Noun" },
  { kana:"くがつ", romaji:"kugatsu", reading:"くがつ", meaning:"September", type:"Noun" },
  { kana:"じゅうがつ", romaji:"juugatsu", reading:"じゅうがつ", meaning:"October", type:"Noun" },
  { kana:"じゅういちがつ", romaji:"juuichigatsu", reading:"じゅういちがつ", meaning:"November", type:"Noun" },
  { kana:"じゅうにがつ", romaji:"juunigatsu", reading:"じゅうにがつ", meaning:"December", type:"Noun" },
  { kana:"まいにち", romaji:"mainichi", reading:"まいにち", meaning:"every day", type:"Adverb" },
  { kana:"まいあさ", romaji:"maiasa", reading:"まいあさ", meaning:"every morning", type:"Adverb" },
  { kana:"まいばん", romaji:"maiban", reading:"まいばん", meaning:"every evening", type:"Adverb" },
  { kana:"まいしゅう", romaji:"maishuu", reading:"まいしゅう", meaning:"every week", type:"Adverb" },
  { kana:"まいつき", romaji:"maitsuki", reading:"まいつき", meaning:"every month", type:"Adverb" },
  { kana:"まいとし", romaji:"maitoshi", reading:"まいとし", meaning:"every year", type:"Adverb" },
  { kana:"がくせい", romaji:"gakusei", reading:"がくせい", meaning:"student", type:"Noun" },
  { kana:"せんせい", romaji:"sensei", reading:"せんせい", meaning:"teacher", type:"Noun" },
  { kana:"きょうかしょ", romaji:"kyoukasho", reading:"きょうかしょ", meaning:"textbook", type:"Noun" },
  { kana:"しゅくだい", romaji:"shukudai", reading:"しゅくだい", meaning:"homework", type:"Noun" },
  { kana:"しけん", romaji:"shiken", reading:"しけん", meaning:"exam / test", type:"Noun" },
  { kana:"べんきょう", romaji:"benkyou", reading:"べんきょう", meaning:"study / studying", type:"Noun" },
  { kana:"しごと", romaji:"shigoto", reading:"しごと", meaning:"work / job", type:"Noun" },
  { kana:"かいしゃいん", romaji:"kaishain", reading:"かいしゃいん", meaning:"company employee", type:"Noun" },
  { kana:"いしゃ", romaji:"isha", reading:"いしゃ", meaning:"doctor", type:"Noun" },
  { kana:"かんごし", romaji:"kangoshi", reading:"かんごし", meaning:"nurse", type:"Noun" },
  { kana:"りょうり", romaji:"ryouri", reading:"りょうり", meaning:"cooking / cuisine", type:"Noun" },
  { kana:"かいもの", romaji:"kaimono", reading:"かいもの", meaning:"shopping", type:"Noun" },
  { kana:"なまえ", romaji:"namae", reading:"なまえ", meaning:"name", type:"Noun" },
  { kana:"じゅうしょ", romaji:"juusho", reading:"じゅうしょ", meaning:"address", type:"Noun" },
  { kana:"ことば", romaji:"kotoba", reading:"ことば", meaning:"word / language", type:"Noun" },
  { kana:"にほんご", romaji:"nihongo", reading:"にほんご", meaning:"Japanese language", type:"Noun" },
  { kana:"えいご", romaji:"eigo", reading:"えいご", meaning:"English language", type:"Noun" },
  { kana:"もんだい", romaji:"mondai", reading:"もんだい", meaning:"problem / question", type:"Noun" },
  { kana:"こたえ", romaji:"kotae", reading:"こたえ", meaning:"answer", type:"Noun" },
  { kana:"おんがく", romaji:"ongaku", reading:"おんがく", meaning:"music", type:"Noun" },
  { kana:"えいが", romaji:"eiga", reading:"えいが", meaning:"movie", type:"Noun" },
  { kana:"りょこう", romaji:"ryokou", reading:"りょこう", meaning:"travel / trip", type:"Noun" },
  { kana:"さんぽ", romaji:"sanpo", reading:"さんぽ", meaning:"walk / stroll", type:"Noun" },
  { kana:"スポーツ", romaji:"supootsu", reading:"スポーツ", meaning:"sports", type:"Noun" },
  { kana:"しゅみ", romaji:"shumi", reading:"しゅみ", meaning:"hobby", type:"Noun" },
  { kana:"びょうき", romaji:"byouki", reading:"びょうき", meaning:"illness / disease", type:"Noun" },
  { kana:"くすり", romaji:"kusuri", reading:"くすり", meaning:"medicine", type:"Noun" },
  { kana:"おかね", romaji:"okane", reading:"おかね", meaning:"money", type:"Noun" },
  { kana:"ねだん", romaji:"nedan", reading:"ねだん", meaning:"price", type:"Noun" },
  { kana:"しゃしん", romaji:"shashin", reading:"しゃしん", meaning:"photograph", type:"Noun" },
  { kana:"てんき", romaji:"tenki", reading:"てんき", meaning:"weather", type:"Noun" },
  { kana:"はれ", romaji:"hare", reading:"はれ", meaning:"sunny / clear", type:"Noun" },
  { kana:"くもり", romaji:"kumori", reading:"くもり", meaning:"cloudy", type:"Noun" },
  { kana:"あめ（雨）", romaji:"ame", reading:"あめ", meaning:"rain", type:"Noun" },
  { kana:"ゆき", romaji:"yuki", reading:"ゆき", meaning:"snow", type:"Noun" },
  { kana:"かぜ（風）", romaji:"kaze", reading:"かぜ", meaning:"wind", type:"Noun" },
  { kana:"たいふう", romaji:"taifuu", reading:"たいふう", meaning:"typhoon", type:"Noun" },
  { kana:"じしん", romaji:"jishin", reading:"じしん", meaning:"earthquake", type:"Noun" },
  { kana:"そら", romaji:"sora", reading:"そら", meaning:"sky", type:"Noun" },
  { kana:"うみ", romaji:"umi", reading:"うみ", meaning:"sea / ocean", type:"Noun" },
  { kana:"かわ", romaji:"kawa", reading:"かわ", meaning:"river", type:"Noun" },
  { kana:"やま", romaji:"yama", reading:"やま", meaning:"mountain", type:"Noun" },
  { kana:"もり", romaji:"mori", reading:"もり", meaning:"forest", type:"Noun" },
  { kana:"はな（花）", romaji:"hana", reading:"はな", meaning:"flower", type:"Noun" },
  { kana:"き", romaji:"ki", reading:"き", meaning:"tree", type:"Noun" },
  { kana:"くさ", romaji:"kusa", reading:"くさ", meaning:"grass", type:"Noun" },
  { kana:"つき（月）", romaji:"tsuki", reading:"つき", meaning:"moon / month", type:"Noun" },
  { kana:"ほし", romaji:"hoshi", reading:"ほし", meaning:"star", type:"Noun" },
  { kana:"たいよう", romaji:"taiyou", reading:"たいよう", meaning:"sun", type:"Noun" },
  { kana:"こおり", romaji:"koori", reading:"こおり", meaning:"ice", type:"Noun" },
  { kana:"はる", romaji:"haru", reading:"はる", meaning:"spring (season)", type:"Noun" },
  { kana:"なつ", romaji:"natsu", reading:"なつ", meaning:"summer", type:"Noun" },
  { kana:"あき", romaji:"aki", reading:"あき", meaning:"autumn / fall", type:"Noun" },
  { kana:"ふゆ", romaji:"fuyu", reading:"ふゆ", meaning:"winter", type:"Noun" },
  { kana:"あか", romaji:"aka", reading:"あか", meaning:"red", type:"Noun (Color)" },
  { kana:"あお", romaji:"ao", reading:"あお", meaning:"blue / green", type:"Noun (Color)" },
  { kana:"しろ", romaji:"shiro", reading:"しろ", meaning:"white", type:"Noun (Color)" },
  { kana:"くろ", romaji:"kuro", reading:"くろ", meaning:"black", type:"Noun (Color)" },
  { kana:"きいろ", romaji:"kiiro", reading:"きいろ", meaning:"yellow", type:"Noun (Color)" },
  { kana:"みどり", romaji:"midori", reading:"みどり", meaning:"green", type:"Noun (Color)" },
  { kana:"むらさき", romaji:"murasaki", reading:"むらさき", meaning:"purple", type:"Noun (Color)" },
  { kana:"ピンク", romaji:"pinku", reading:"ピンク", meaning:"pink", type:"Noun (Color)" },
  { kana:"オレンジ", romaji:"orenji", reading:"オレンジ", meaning:"orange (color)", type:"Noun (Color)" },
  { kana:"ちゃいろ", romaji:"chairo", reading:"ちゃいろ", meaning:"brown", type:"Noun (Color)" },
  { kana:"はいいろ", romaji:"haiiro", reading:"はいいろ", meaning:"grey", type:"Noun (Color)" },
  { kana:"あう", romaji:"au", reading:"あう", meaning:"to meet", type:"Verb, Godan" },
  { kana:"あく", romaji:"aku", reading:"あく", meaning:"to open (intrans.)", type:"Verb, Godan" },
  { kana:"あそぶ", romaji:"asobu", reading:"あそぶ", meaning:"to play", type:"Verb, Godan" },
  { kana:"あらう", romaji:"arau", reading:"あらう", meaning:"to wash", type:"Verb, Godan" },
  { kana:"ある", romaji:"aru", reading:"ある", meaning:"to exist / to have (inanimate)", type:"Verb, Godan" },
  { kana:"あるく", romaji:"aruku", reading:"あるく", meaning:"to walk", type:"Verb, Godan" },
  { kana:"いう", romaji:"iu", reading:"いう", meaning:"to say", type:"Verb, Godan" },
  { kana:"いく", romaji:"iku", reading:"いく", meaning:"to go", type:"Verb, Godan" },
  { kana:"いそぐ", romaji:"isogu", reading:"いそぐ", meaning:"to hurry", type:"Verb, Godan" },
  { kana:"うごく", romaji:"ugoku", reading:"うごく", meaning:"to move", type:"Verb, Godan" },
  { kana:"うたう", romaji:"utau", reading:"うたう", meaning:"to sing", type:"Verb, Godan" },
  { kana:"うる", romaji:"uru", reading:"うる", meaning:"to sell", type:"Verb, Godan" },
  { kana:"おく", romaji:"oku", reading:"おく", meaning:"to put / place", type:"Verb, Godan" },
  { kana:"おもう", romaji:"omou", reading:"おもう", meaning:"to think", type:"Verb, Godan" },
  { kana:"およぐ", romaji:"oyogu", reading:"およぐ", meaning:"to swim", type:"Verb, Godan" },
  { kana:"おわる", romaji:"owaru", reading:"おわる", meaning:"to end / finish (intrans.)", type:"Verb, Godan" },
  { kana:"かう", romaji:"kau", reading:"かう", meaning:"to buy", type:"Verb, Godan" },
  { kana:"かえる（帰る）", romaji:"kaeru", reading:"かえる", meaning:"to return home", type:"Verb, Godan" },
  { kana:"かく", romaji:"kaku", reading:"かく", meaning:"to write", type:"Verb, Godan" },
  { kana:"かす", romaji:"kasu", reading:"かす", meaning:"to lend", type:"Verb, Godan" },
  { kana:"きく", romaji:"kiku", reading:"きく", meaning:"to listen / hear / ask", type:"Verb, Godan" },
  { kana:"きる（切る）", romaji:"kiru", reading:"きる", meaning:"to cut", type:"Verb, Godan" },
  { kana:"けす", romaji:"kesu", reading:"けす", meaning:"to turn off / erase", type:"Verb, Godan" },
  { kana:"こまる", romaji:"komaru", reading:"こまる", meaning:"to be troubled", type:"Verb, Godan" },
  { kana:"しぬ", romaji:"shinu", reading:"しぬ", meaning:"to die", type:"Verb, Godan" },
  { kana:"しる", romaji:"shiru", reading:"しる", meaning:"to know", type:"Verb, Godan" },
  { kana:"すむ", romaji:"sumu", reading:"すむ", meaning:"to live / reside", type:"Verb, Godan" },
  { kana:"たつ", romaji:"tatsu", reading:"たつ", meaning:"to stand up", type:"Verb, Godan" },
  { kana:"たのむ", romaji:"tanomu", reading:"たのむ", meaning:"to request / ask", type:"Verb, Godan" },
  { kana:"ちがう", romaji:"chigau", reading:"ちがう", meaning:"to be different / wrong", type:"Verb, Godan" },
  { kana:"つかう", romaji:"tsukau", reading:"つかう", meaning:"to use", type:"Verb, Godan" },
  { kana:"つく", romaji:"tsuku", reading:"つく", meaning:"to arrive", type:"Verb, Godan" },
  { kana:"てつだう", romaji:"tetsudau", reading:"てつだう", meaning:"to help / assist", type:"Verb, Godan" },
  { kana:"とまる", romaji:"tomaru", reading:"とまる", meaning:"to stop / stay overnight", type:"Verb, Godan" },
  { kana:"とる", romaji:"toru", reading:"とる", meaning:"to take", type:"Verb, Godan" },
  { kana:"なる", romaji:"naru", reading:"なる", meaning:"to become", type:"Verb, Godan" },
  { kana:"ぬぐ", romaji:"nugu", reading:"ぬぐ", meaning:"to take off (clothes)", type:"Verb, Godan" },
  { kana:"のむ", romaji:"nomu", reading:"のむ", meaning:"to drink", type:"Verb, Godan" },
  { kana:"のる", romaji:"noru", reading:"のる", meaning:"to ride / get on", type:"Verb, Godan" },
  { kana:"はいる", romaji:"hairu", reading:"はいる", meaning:"to enter", type:"Verb, Godan" },
  { kana:"はしる", romaji:"hashiru", reading:"はしる", meaning:"to run", type:"Verb, Godan" },
  { kana:"はたらく", romaji:"hataraku", reading:"はたらく", meaning:"to work", type:"Verb, Godan" },
  { kana:"はなす", romaji:"hanasu", reading:"はなす", meaning:"to speak / talk", type:"Verb, Godan" },
  { kana:"ひく", romaji:"hiku", reading:"ひく", meaning:"to pull / play (instrument)", type:"Verb, Godan" },
  { kana:"まつ", romaji:"matsu", reading:"まつ", meaning:"to wait", type:"Verb, Godan" },
  { kana:"もつ", romaji:"motsu", reading:"もつ", meaning:"to hold / carry", type:"Verb, Godan" },
  { kana:"やすむ", romaji:"yasumu", reading:"やすむ", meaning:"to rest", type:"Verb, Godan" },
  { kana:"よぶ", romaji:"yobu", reading:"よぶ", meaning:"to call / invite", type:"Verb, Godan" },
  { kana:"よむ", romaji:"yomu", reading:"よむ", meaning:"to read", type:"Verb, Godan" },
  { kana:"わかる", romaji:"wakaru", reading:"わかる", meaning:"to understand", type:"Verb, Godan" },
  { kana:"わたす", romaji:"watasu", reading:"わたす", meaning:"to hand over", type:"Verb, Godan" },
  { kana:"わたる", romaji:"wataru", reading:"わたる", meaning:"to cross", type:"Verb, Godan" },
  { kana:"ふる", romaji:"furu", reading:"ふる", meaning:"to fall (rain / snow)", type:"Verb, Godan" },
  { kana:"ならぶ", romaji:"narabu", reading:"ならぶ", meaning:"to line up", type:"Verb, Godan" },
  { kana:"さがす", romaji:"sagasu", reading:"さがす", meaning:"to search for", type:"Verb, Godan" },
  { kana:"おす", romaji:"osu", reading:"おす", meaning:"to push", type:"Verb, Godan" },
  { kana:"あける", romaji:"akeru", reading:"あける", meaning:"to open (trans.)", type:"Verb, Ichidan" },
  { kana:"あげる", romaji:"ageru", reading:"あげる", meaning:"to give (to others)", type:"Verb, Ichidan" },
  { kana:"あびる", romaji:"abiru", reading:"あびる", meaning:"to bathe / shower", type:"Verb, Ichidan" },
  { kana:"いきる", romaji:"ikiru", reading:"いきる", meaning:"to live", type:"Verb, Ichidan" },
  { kana:"いれる", romaji:"ireru", reading:"いれる", meaning:"to put in", type:"Verb, Ichidan" },
  { kana:"うまれる", romaji:"umareru", reading:"うまれる", meaning:"to be born", type:"Verb, Ichidan" },
  { kana:"うける", romaji:"ukeru", reading:"うける", meaning:"to receive / take (exam)", type:"Verb, Ichidan" },
  { kana:"おきる", romaji:"okiru", reading:"おきる", meaning:"to wake up / get up", type:"Verb, Ichidan" },
  { kana:"おしえる", romaji:"oshieru", reading:"おしえる", meaning:"to teach / tell", type:"Verb, Ichidan" },
  { kana:"おぼえる", romaji:"oboeru", reading:"おぼえる", meaning:"to remember / memorize", type:"Verb, Ichidan" },
  { kana:"おりる", romaji:"oriru", reading:"おりる", meaning:"to get off / descend", type:"Verb, Ichidan" },
  { kana:"かりる", romaji:"kariru", reading:"かりる", meaning:"to borrow", type:"Verb, Ichidan" },
  { kana:"かんがえる", romaji:"kangaeru", reading:"かんがえる", meaning:"to think / consider", type:"Verb, Ichidan" },
  { kana:"きる（着る）", romaji:"kiru", reading:"きる", meaning:"to wear (clothing)", type:"Verb, Ichidan" },
  { kana:"きこえる", romaji:"kikoeru", reading:"きこえる", meaning:"to be audible / can hear", type:"Verb, Ichidan" },
  { kana:"くれる", romaji:"kureru", reading:"くれる", meaning:"to give (to me)", type:"Verb, Ichidan" },
  { kana:"こたえる", romaji:"kotaeru", reading:"こたえる", meaning:"to answer", type:"Verb, Ichidan" },
  { kana:"しめる", romaji:"shimeru", reading:"しめる", meaning:"to close (trans.)", type:"Verb, Ichidan" },
  { kana:"しらべる", romaji:"shiraberu", reading:"しらべる", meaning:"to check / investigate", type:"Verb, Ichidan" },
  { kana:"すてる", romaji:"suteru", reading:"すてる", meaning:"to throw away", type:"Verb, Ichidan" },
  { kana:"たべる", romaji:"taberu", reading:"たべる", meaning:"to eat", type:"Verb, Ichidan" },
  { kana:"つかれる", romaji:"tsukareru", reading:"つかれる", meaning:"to get tired", type:"Verb, Ichidan" },
  { kana:"つける", romaji:"tsukeru", reading:"つける", meaning:"to turn on / attach", type:"Verb, Ichidan" },
  { kana:"でかける", romaji:"dekakeru", reading:"でかける", meaning:"to go out", type:"Verb, Ichidan" },
  { kana:"でる", romaji:"deru", reading:"でる", meaning:"to leave / come out", type:"Verb, Ichidan" },
  { kana:"とめる", romaji:"tomeru", reading:"とめる", meaning:"to stop (trans.)", type:"Verb, Ichidan" },
  { kana:"ねる", romaji:"neru", reading:"ねる", meaning:"to sleep / go to bed", type:"Verb, Ichidan" },
  { kana:"はじめる", romaji:"hajimeru", reading:"はじめる", meaning:"to begin / start", type:"Verb, Ichidan" },
  { kana:"まける", romaji:"makeru", reading:"まける", meaning:"to lose", type:"Verb, Ichidan" },
  { kana:"みえる", romaji:"mieru", reading:"みえる", meaning:"to be visible / can see", type:"Verb, Ichidan" },
  { kana:"みせる", romaji:"miseru", reading:"みせる", meaning:"to show", type:"Verb, Ichidan" },
  { kana:"みる", romaji:"miru", reading:"みる", meaning:"to see / watch / look", type:"Verb, Ichidan" },
  { kana:"やめる", romaji:"yameru", reading:"やめる", meaning:"to quit / stop", type:"Verb, Ichidan" },
  { kana:"わすれる", romaji:"wasureru", reading:"わすれる", meaning:"to forget", type:"Verb, Ichidan" },
  { kana:"くる", romaji:"kuru", reading:"くる", meaning:"to come", type:"Verb, Irregular" },
  { kana:"する", romaji:"suru", reading:"する", meaning:"to do", type:"Verb, Irregular" },
  { kana:"べんきょうする", romaji:"benkyou suru", reading:"べんきょうする", meaning:"to study", type:"Verb, Irregular" },
  { kana:"りょこうする", romaji:"ryokou suru", reading:"りょこうする", meaning:"to travel", type:"Verb, Irregular" },
  { kana:"さんぽする", romaji:"sanpo suru", reading:"さんぽする", meaning:"to take a walk", type:"Verb, Irregular" },
  { kana:"でんわする", romaji:"denwa suru", reading:"でんわする", meaning:"to phone / call", type:"Verb, Irregular" },
  { kana:"せんたくする", romaji:"sentaku suru", reading:"せんたくする", meaning:"to do laundry", type:"Verb, Irregular" },
  { kana:"そうじする", romaji:"souji suru", reading:"そうじする", meaning:"to clean", type:"Verb, Irregular" },
  { kana:"りょうりする", romaji:"ryouri suru", reading:"りょうりする", meaning:"to cook", type:"Verb, Irregular" },
  { kana:"うんどうする", romaji:"undou suru", reading:"うんどうする", meaning:"to exercise", type:"Verb, Irregular" },
  { kana:"かいものする", romaji:"kaimono suru", reading:"かいものする", meaning:"to go shopping", type:"Verb, Irregular" },
  { kana:"あかい", romaji:"akai", reading:"あかい", meaning:"red", type:"i-Adjective" },
  { kana:"あおい", romaji:"aoi", reading:"あおい", meaning:"blue / green", type:"i-Adjective" },
  { kana:"しろい", romaji:"shiroi", reading:"しろい", meaning:"white", type:"i-Adjective" },
  { kana:"くろい", romaji:"kuroi", reading:"くろい", meaning:"black", type:"i-Adjective" },
  { kana:"きいろい", romaji:"kiiroi", reading:"きいろい", meaning:"yellow", type:"i-Adjective" },
  { kana:"おおきい", romaji:"ookii", reading:"おおきい", meaning:"big / large", type:"i-Adjective" },
  { kana:"ちいさい", romaji:"chiisai", reading:"ちいさい", meaning:"small", type:"i-Adjective" },
  { kana:"たかい", romaji:"takai", reading:"たかい", meaning:"tall / expensive", type:"i-Adjective" },
  { kana:"ひくい", romaji:"hikui", reading:"ひくい", meaning:"low / short (height)", type:"i-Adjective" },
  { kana:"ながい", romaji:"nagai", reading:"ながい", meaning:"long", type:"i-Adjective" },
  { kana:"みじかい", romaji:"mijikai", reading:"みじかい", meaning:"short (length)", type:"i-Adjective" },
  { kana:"おおい", romaji:"ooi", reading:"おおい", meaning:"many / much", type:"i-Adjective" },
  { kana:"すくない", romaji:"sukunai", reading:"すくない", meaning:"few / little", type:"i-Adjective" },
  { kana:"あたらしい", romaji:"atarashii", reading:"あたらしい", meaning:"new", type:"i-Adjective" },
  { kana:"ふるい", romaji:"furui", reading:"ふるい", meaning:"old (things)", type:"i-Adjective" },
  { kana:"わかい", romaji:"wakai", reading:"わかい", meaning:"young", type:"i-Adjective" },
  { kana:"よい・いい", romaji:"yoi / ii", reading:"よい・いい", meaning:"good", type:"i-Adjective" },
  { kana:"わるい", romaji:"warui", reading:"わるい", meaning:"bad", type:"i-Adjective" },
  { kana:"あつい（暑い）", romaji:"atsui", reading:"あつい", meaning:"hot (weather / temp)", type:"i-Adjective" },
  { kana:"さむい", romaji:"samui", reading:"さむい", meaning:"cold", type:"i-Adjective" },
  { kana:"すずしい", romaji:"suzushii", reading:"すずしい", meaning:"cool", type:"i-Adjective" },
  { kana:"あたたかい", romaji:"atatakai", reading:"あたたかい", meaning:"warm", type:"i-Adjective" },
  { kana:"からい", romaji:"karai", reading:"からい", meaning:"spicy / salty", type:"i-Adjective" },
  { kana:"あまい", romaji:"amai", reading:"あまい", meaning:"sweet", type:"i-Adjective" },
  { kana:"すっぱい", romaji:"suppai", reading:"すっぱい", meaning:"sour", type:"i-Adjective" },
  { kana:"にがい", romaji:"nigai", reading:"にがい", meaning:"bitter", type:"i-Adjective" },
  { kana:"おいしい", romaji:"oishii", reading:"おいしい", meaning:"delicious", type:"i-Adjective" },
  { kana:"まずい", romaji:"mazui", reading:"まずい", meaning:"bad tasting", type:"i-Adjective" },
  { kana:"たのしい", romaji:"tanoshii", reading:"たのしい", meaning:"fun / enjoyable", type:"i-Adjective" },
  { kana:"かなしい", romaji:"kanashii", reading:"かなしい", meaning:"sad", type:"i-Adjective" },
  { kana:"うれしい", romaji:"ureshii", reading:"うれしい", meaning:"happy / glad", type:"i-Adjective" },
  { kana:"こわい", romaji:"kowai", reading:"こわい", meaning:"scary", type:"i-Adjective" },
  { kana:"むずかしい", romaji:"muzukashii", reading:"むずかしい", meaning:"difficult", type:"i-Adjective" },
  { kana:"やさしい", romaji:"yasashii", reading:"やさしい", meaning:"easy / kind", type:"i-Adjective" },
  { kana:"おもしろい", romaji:"omoshiroi", reading:"おもしろい", meaning:"interesting / funny", type:"i-Adjective" },
  { kana:"つまらない", romaji:"tsumaranai", reading:"つまらない", meaning:"boring", type:"i-Adjective" },
  { kana:"いそがしい", romaji:"isogashii", reading:"いそがしい", meaning:"busy", type:"i-Adjective" },
  { kana:"はやい", romaji:"hayai", reading:"はやい", meaning:"fast / early", type:"i-Adjective" },
  { kana:"おそい", romaji:"osoi", reading:"おそい", meaning:"slow / late", type:"i-Adjective" },
  { kana:"つよい", romaji:"tsuyoi", reading:"つよい", meaning:"strong", type:"i-Adjective" },
  { kana:"よわい", romaji:"yowai", reading:"よわい", meaning:"weak", type:"i-Adjective" },
  { kana:"かるい", romaji:"karui", reading:"かるい", meaning:"light (weight)", type:"i-Adjective" },
  { kana:"おもい", romaji:"omoi", reading:"おもい", meaning:"heavy", type:"i-Adjective" },
  { kana:"やわらかい", romaji:"yawarakai", reading:"やわらかい", meaning:"soft", type:"i-Adjective" },
  { kana:"かたい", romaji:"katai", reading:"かたい", meaning:"hard / tough", type:"i-Adjective" },
  { kana:"あかるい", romaji:"akarui", reading:"あかるい", meaning:"bright / cheerful", type:"i-Adjective" },
  { kana:"くらい", romaji:"kurai", reading:"くらい", meaning:"dark", type:"i-Adjective" },
  { kana:"ひろい", romaji:"hiroi", reading:"ひろい", meaning:"wide / spacious", type:"i-Adjective" },
  { kana:"せまい", romaji:"semai", reading:"せまい", meaning:"narrow / small (space)", type:"i-Adjective" },
  { kana:"とおい", romaji:"tooi", reading:"とおい", meaning:"far", type:"i-Adjective" },
  { kana:"ちかい", romaji:"chikai", reading:"ちかい", meaning:"near / close", type:"i-Adjective" },
  { kana:"やすい", romaji:"yasui", reading:"やすい", meaning:"cheap / inexpensive", type:"i-Adjective" },
  { kana:"あぶない", romaji:"abunai", reading:"あぶない", meaning:"dangerous", type:"i-Adjective" },
  { kana:"いたい", romaji:"itai", reading:"いたい", meaning:"painful / it hurts", type:"i-Adjective" },
  { kana:"ねむい", romaji:"nemui", reading:"ねむい", meaning:"sleepy", type:"i-Adjective" },
  { kana:"かわいい", romaji:"kawaii", reading:"かわいい", meaning:"cute", type:"i-Adjective" },
  { kana:"うつくしい", romaji:"utsukushii", reading:"うつくしい", meaning:"beautiful", type:"i-Adjective" },
  { kana:"ただしい", romaji:"tadashii", reading:"ただしい", meaning:"correct / right", type:"i-Adjective" },
  { kana:"きれい", romaji:"kirei", reading:"きれい", meaning:"pretty / clean", type:"na-Adjective" },
  { kana:"しずか", romaji:"shizuka", reading:"しずか", meaning:"quiet", type:"na-Adjective" },
  { kana:"にぎやか", romaji:"nigiyaka", reading:"にぎやか", meaning:"lively / bustling", type:"na-Adjective" },
  { kana:"すき", romaji:"suki", reading:"すき", meaning:"liked / to like", type:"na-Adjective" },
  { kana:"きらい", romaji:"kirai", reading:"きらい", meaning:"disliked", type:"na-Adjective" },
  { kana:"じょうず", romaji:"jouzu", reading:"じょうず", meaning:"skilled / good at", type:"na-Adjective" },
  { kana:"へた", romaji:"heta", reading:"へた", meaning:"unskilled / not good at", type:"na-Adjective" },
  { kana:"げんき", romaji:"genki", reading:"げんき", meaning:"healthy / energetic", type:"na-Adjective" },
  { kana:"たいせつ", romaji:"taisetsu", reading:"たいせつ", meaning:"important / precious", type:"na-Adjective" },
  { kana:"べんり", romaji:"benri", reading:"べんり", meaning:"convenient", type:"na-Adjective" },
  { kana:"ゆうめい", romaji:"yuumei", reading:"ゆうめい", meaning:"famous", type:"na-Adjective" },
  { kana:"しんせつ", romaji:"shinsetsu", reading:"しんせつ", meaning:"kind / helpful", type:"na-Adjective" },
  { kana:"まじめ", romaji:"majime", reading:"まじめ", meaning:"serious / diligent", type:"na-Adjective" },
  { kana:"ひま", romaji:"hima", reading:"ひま", meaning:"free (not busy)", type:"na-Adjective" },
  { kana:"だいすき", romaji:"daisuki", reading:"だいすき", meaning:"love / like a lot", type:"na-Adjective" },
  { kana:"かんたん", romaji:"kantan", reading:"かんたん", meaning:"simple / easy", type:"na-Adjective" },
  { kana:"ふつう", romaji:"futsuu", reading:"ふつう", meaning:"ordinary / normal", type:"na-Adjective" },
  { kana:"すてき", romaji:"suteki", reading:"すてき", meaning:"wonderful / lovely", type:"na-Adjective" },
  { kana:"しあわせ", romaji:"shiawase", reading:"しあわせ", meaning:"happy / fortunate", type:"na-Adjective" },
  { kana:"あんぜん", romaji:"anzen", reading:"あんぜん", meaning:"safe", type:"na-Adjective" },
  { kana:"たいへん", romaji:"taihen", reading:"たいへん", meaning:"difficult / terrible", type:"na-Adjective" },
  { kana:"にぎやか", romaji:"nigiyaka", reading:"にぎやか", meaning:"lively / busy (place)", type:"na-Adjective" },
  { kana:"とくい", romaji:"tokui", reading:"とくい", meaning:"good at / proud", type:"na-Adjective" },
  { kana:"にがて", romaji:"nigate", reading:"にがて", meaning:"not good at / weak point", type:"na-Adjective" },
  { kana:"とても", romaji:"totemo", reading:"とても", meaning:"very", type:"Adverb" },
  { kana:"すごく", romaji:"sugoku", reading:"すごく", meaning:"very / extremely (casual)", type:"Adverb" },
  { kana:"もっと", romaji:"motto", reading:"もっと", meaning:"more", type:"Adverb" },
  { kana:"ちょっと", romaji:"chotto", reading:"ちょっと", meaning:"a little / just a moment", type:"Adverb" },
  { kana:"すこし", romaji:"sukoshi", reading:"すこし", meaning:"a little", type:"Adverb" },
  { kana:"たくさん", romaji:"takusan", reading:"たくさん", meaning:"many / much / a lot", type:"Adverb" },
  { kana:"もう", romaji:"mou", reading:"もう", meaning:"already / anymore", type:"Adverb" },
  { kana:"まだ", romaji:"mada", reading:"まだ", meaning:"still / not yet", type:"Adverb" },
  { kana:"また", romaji:"mata", reading:"また", meaning:"again", type:"Adverb" },
  { kana:"いつも", romaji:"itsumo", reading:"いつも", meaning:"always", type:"Adverb" },
  { kana:"ときどき", romaji:"tokidoki", reading:"ときどき", meaning:"sometimes", type:"Adverb" },
  { kana:"たいてい", romaji:"taitei", reading:"たいてい", meaning:"usually", type:"Adverb" },
  { kana:"よく", romaji:"yoku", reading:"よく", meaning:"often / well", type:"Adverb" },
  { kana:"ぜんぜん", romaji:"zenzen", reading:"ぜんぜん", meaning:"not at all (with negative)", type:"Adverb" },
  { kana:"はやく", romaji:"hayaku", reading:"はやく", meaning:"quickly / early", type:"Adverb" },
  { kana:"おそく", romaji:"osoku", reading:"おそく", meaning:"slowly / late", type:"Adverb" },
  { kana:"いっしょに", romaji:"issho ni", reading:"いっしょに", meaning:"together", type:"Adverb" },
  { kana:"ひとりで", romaji:"hitori de", reading:"ひとりで", meaning:"alone / by oneself", type:"Adverb" },
  { kana:"だいたい", romaji:"daitai", reading:"だいたい", meaning:"approximately / mostly", type:"Adverb" },
  { kana:"もちろん", romaji:"mochiron", reading:"もちろん", meaning:"of course", type:"Adverb" },
  { kana:"たぶん", romaji:"tabun", reading:"たぶん", meaning:"probably / perhaps", type:"Adverb" },
  { kana:"すぐ", romaji:"sugu", reading:"すぐ", meaning:"immediately / soon", type:"Adverb" },
  { kana:"はじめて", romaji:"hajimete", reading:"はじめて", meaning:"for the first time", type:"Adverb" },
  { kana:"ぜひ", romaji:"zehi", reading:"ぜひ", meaning:"by all means / definitely", type:"Adverb" },
  { kana:"あまり", romaji:"amari", reading:"あまり", meaning:"not very (with negative)", type:"Adverb" },
  { kana:"まず", romaji:"mazu", reading:"まず", meaning:"first of all", type:"Adverb" },
  { kana:"つぎに", romaji:"tsugi ni", reading:"つぎに", meaning:"next", type:"Adverb" },
  { kana:"さいごに", romaji:"saigo ni", reading:"さいごに", meaning:"finally / lastly", type:"Adverb" },
  { kana:"そして", romaji:"soshite", reading:"そして", meaning:"and then / and", type:"Conjunction" },
  { kana:"それから", romaji:"sorekara", reading:"それから", meaning:"after that / and then", type:"Conjunction" },
  { kana:"でも", romaji:"demo", reading:"でも", meaning:"but / however", type:"Conjunction" },
  { kana:"だから", romaji:"dakara", reading:"だから", meaning:"so / therefore", type:"Conjunction" },
  { kana:"しかし", romaji:"shikashi", reading:"しかし", meaning:"however (formal)", type:"Conjunction" },
  { kana:"それに", romaji:"sore ni", reading:"それに", meaning:"furthermore / besides", type:"Conjunction" },
  { kana:"または", romaji:"matawa", reading:"または", meaning:"or", type:"Conjunction" },
  { kana:"もし", romaji:"moshi", reading:"もし", meaning:"if", type:"Conjunction" },
  { kana:"ところで", romaji:"tokoro de", reading:"ところで", meaning:"by the way", type:"Conjunction" },
  { kana:"うえ", romaji:"ue", reading:"うえ", meaning:"above / up / on top", type:"Noun (Position)" },
  { kana:"した", romaji:"shita", reading:"した", meaning:"below / under", type:"Noun (Position)" },
  { kana:"みぎ", romaji:"migi", reading:"みぎ", meaning:"right (direction)", type:"Noun (Position)" },
  { kana:"ひだり", romaji:"hidari", reading:"ひだり", meaning:"left (direction)", type:"Noun (Position)" },
  { kana:"なか", romaji:"naka", reading:"なか", meaning:"inside / middle", type:"Noun (Position)" },
  { kana:"そと", romaji:"soto", reading:"そと", meaning:"outside", type:"Noun (Position)" },
  { kana:"まえ", romaji:"mae", reading:"まえ", meaning:"front / before", type:"Noun (Position)" },
  { kana:"うしろ", romaji:"ushiro", reading:"うしろ", meaning:"behind / back", type:"Noun (Position)" },
  { kana:"よこ", romaji:"yoko", reading:"よこ", meaning:"side / beside", type:"Noun (Position)" },
  { kana:"ちかく", romaji:"chikaku", reading:"ちかく", meaning:"nearby / close to", type:"Noun (Position)" },
  { kana:"とおく", romaji:"tooku", reading:"とおく", meaning:"far away / in the distance", type:"Noun (Position)" },
  { kana:"あいだ", romaji:"aida", reading:"あいだ", meaning:"between / among", type:"Noun (Position)" },
  { kana:"かど", romaji:"kado", reading:"かど", meaning:"corner", type:"Noun (Position)" },
  { kana:"ひとつ", romaji:"hitotsu", reading:"ひとつ", meaning:"one (general counter)", type:"Noun" },
  { kana:"ふたつ", romaji:"futatsu", reading:"ふたつ", meaning:"two (general counter)", type:"Noun" },
  { kana:"みっつ", romaji:"mittsu", reading:"みっつ", meaning:"three (general counter)", type:"Noun" },
  { kana:"よっつ", romaji:"yottsu", reading:"よっつ", meaning:"four (general counter)", type:"Noun" },
  { kana:"いつつ", romaji:"itsutsu", reading:"いつつ", meaning:"five (general counter)", type:"Noun" },
  { kana:"むっつ", romaji:"muttsu", reading:"むっつ", meaning:"six (general counter)", type:"Noun" },
  { kana:"ななつ", romaji:"nanatsu", reading:"ななつ", meaning:"seven (general counter)", type:"Noun" },
  { kana:"やっつ", romaji:"yattsu", reading:"やっつ", meaning:"eight (general counter)", type:"Noun" },
  { kana:"ここのつ", romaji:"kokonotsu", reading:"ここのつ", meaning:"nine (general counter)", type:"Noun" },
  { kana:"とお", romaji:"too", reading:"とお", meaning:"ten (general counter)", type:"Noun" },
  { kana:"なんにん", romaji:"nannin", reading:"なんにん", meaning:"how many people", type:"Noun" },
  { kana:"なんさい", romaji:"nansai", reading:"なんさい", meaning:"how old", type:"Noun" },
  { kana:"せかい", romaji:"sekai", reading:"せかい", meaning:"world", type:"Noun" },
  { kana:"ぶんか", romaji:"bunka", reading:"ぶんか", meaning:"culture", type:"Noun" },
  { kana:"きもの", romaji:"kimono", reading:"きもの", meaning:"kimono", type:"Noun" },
  { kana:"にほん", romaji:"nihon", reading:"にほん", meaning:"Japan", type:"Noun" },
  { kana:"かならず", romaji:"kanarazu", reading:"かならず", meaning:"certainly / without fail", type:"Adverb" },
  { kana:"ほんとう", romaji:"hontou", reading:"ほんとう", meaning:"truth / really", type:"Noun" },
  { kana:"うそ", romaji:"uso", reading:"うそ", meaning:"lie / untruth", type:"Noun" },
  { kana:"いみ", romaji:"imi", reading:"いみ", meaning:"meaning", type:"Noun" },
  { kana:"ちず", romaji:"chizu", reading:"ちず", meaning:"map", type:"Noun" },
  { kana:"かいぎ", romaji:"kaigi", reading:"かいぎ", meaning:"meeting", type:"Noun" },
  { kana:"にゅうがく", romaji:"nyuugaku", reading:"にゅうがく", meaning:"school admission / enrollment", type:"Noun" },
  { kana:"そつぎょう", romaji:"sotsugyou", reading:"そつぎょう", meaning:"graduation", type:"Noun" },
  { kana:"かぜ（風邪）", romaji:"kaze", reading:"かぜ", meaning:"cold (illness)", type:"Noun" },
  { kana:"ねつ", romaji:"netsu", reading:"ねつ", meaning:"fever", type:"Noun" },
  { kana:"りょうきん", romaji:"ryoukin", reading:"りょうきん", meaning:"fee / charge", type:"Noun" },
  { kana:"でんわばんごう", romaji:"denwa bangou", reading:"でんわばんごう", meaning:"phone number", type:"Noun" },
  { kana:"じゆう", romaji:"jiyuu", reading:"じゆう", meaning:"freedom / free", type:"Noun" },
];
